package postgres

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"workflow-optimizer/internal/execution"
)

// ExecutionRepository is the PostgreSQL execution.ExecutionRepository.
//
// Every state change is a compare-and-set (UPDATE ... WHERE id = $1 AND
// status = $2) inside a bounded READ COMMITTED transaction (see
// lifecycleWriter). The row lock taken by UPDATE makes concurrent claims
// across processes serialize on PostgreSQL: exactly one PENDING -> RUNNING can
// match. History is generated by database triggers from the actual status
// change, in the same transaction, with the caller's transition ID as its
// primary key (the commit marker for ambiguous writes).
type ExecutionRepository struct {
	pool   *pgxpool.Pool
	writer *lifecycleWriter
}

var _ execution.ExecutionRepository = (*ExecutionRepository)(nil)

// NewExecutionRepository uses the Store's existing connection pool.
func NewExecutionRepository(store *Store) *ExecutionRepository {
	return &ExecutionRepository{pool: store.Pool, writer: &lifecycleWriter{pool: store.Pool}}
}

const executionColumns = `id, workflow_id, workflow_version_id, status, input, output, error,
       created_at, updated_at, started_at, finished_at, claim_token`

func scanExecution(row pgx.Row) (execution.Execution, error) {
	var (
		e                   execution.Execution
		status              string
		input, output, eerr []byte
	)
	if err := row.Scan(&e.ID, &e.WorkflowID, &e.WorkflowVersionID, &status, &input, &output, &eerr,
		&e.CreatedAt, &e.UpdatedAt, &e.StartedAt, &e.FinishedAt, &e.ClaimToken); err != nil {
		return execution.Execution{}, err
	}
	e.Status = execution.ExecutionStatus(status)
	var err error
	if e.Input, err = decodeMap(input); err != nil {
		return execution.Execution{}, err
	}
	if e.Output, err = decodeMap(output); err != nil {
		return execution.Execution{}, err
	}
	if e.Error, err = decodeError(eerr); err != nil {
		return execution.Execution{}, err
	}
	return e, nil
}

// Create inserts a PENDING execution and returns the persisted row; the
// creation history record is generated by the database in the same
// transaction.
func (r *ExecutionRepository) Create(ctx context.Context, e execution.Execution) (execution.Execution, error) {
	if e.ID == uuid.Nil || e.WorkflowID == uuid.Nil || e.WorkflowVersionID == uuid.Nil {
		return execution.Execution{}, fmt.Errorf("%w: execution, workflow and version IDs are required", execution.ErrInvalidExecution)
	}
	if e.Status != execution.StatusPending || e.StartedAt != nil || e.FinishedAt != nil || e.Output != nil || e.Error != nil || e.ClaimToken != nil {
		return execution.Execution{}, fmt.Errorf("%w: executions are created PENDING without lifecycle data", execution.ErrInvalidExecution)
	}
	input, err := encodeJSON(e.Input)
	if err != nil {
		return execution.Execution{}, fmt.Errorf("%w: encode input: %v", execution.ErrInvalidExecution, err)
	}
	var created execution.Execution
	err = r.writer.write(ctx, nil,
		func(ctx context.Context, tx pgx.Tx) error {
			var scanErr error
			created, scanErr = scanExecution(tx.QueryRow(ctx, `
INSERT INTO executions (id, workflow_id, workflow_version_id, status, input)
VALUES ($1, $2, $3, 'PENDING', $4)
RETURNING `+executionColumns, e.ID, e.WorkflowID, e.WorkflowVersionID, input))
			return scanErr
		},
		func(ctx context.Context) (bool, error) {
			got, getErr := r.Get(ctx, e.ID)
			if errors.Is(getErr, execution.ErrExecutionNotFound) {
				return false, nil
			}
			if getErr != nil {
				return false, getErr
			}
			created = got
			return true, nil
		})
	if err != nil {
		return execution.Execution{}, err
	}
	return created, nil
}

// Get loads one execution.
func (r *ExecutionRepository) Get(ctx context.Context, id uuid.UUID) (execution.Execution, error) {
	e, err := scanExecution(r.pool.QueryRow(ctx, `SELECT `+executionColumns+` FROM executions WHERE id = $1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return execution.Execution{}, fmt.Errorf("%w: %s", execution.ErrExecutionNotFound, id)
	}
	if err != nil {
		return execution.Execution{}, fmt.Errorf("get execution %s: %w", id, err)
	}
	return e, nil
}

// transitionExecutionSQL changes status and the payload that belongs to the
// target status. Timestamps and history are generated by triggers.
const transitionExecutionSQL = `
UPDATE executions SET
    status      = $3::text,
    output      = CASE WHEN $3::text = 'COMPLETED' THEN $4::jsonb ELSE output END,
    error       = CASE WHEN $3::text IN ('FAILED', 'CANCELLED') THEN COALESCE($5::jsonb, error) ELSE error END,
    claim_token = CASE WHEN $3::text = 'RUNNING' THEN $6::uuid ELSE claim_token END
WHERE id = $1 AND status = $2::text`

// sweepRunningNodesSQL finalizes node records that are still RUNNING when the
// execution moves to FAILED or CANCELLED, in the same transaction, so a
// terminal execution never keeps RUNNING nodes.
const sweepRunningNodesSQL = `
UPDATE node_executions SET
    status = 'FAILED',
    error  = jsonb_set($2::jsonb, '{node_id}', to_jsonb(node_id))
WHERE execution_id = $1 AND status = 'RUNNING'`

// Transition performs the atomic compare-and-set described on the type.
func (r *ExecutionRepository) Transition(ctx context.Context, id uuid.UUID, from, to execution.ExecutionStatus, u execution.TransitionUpdate) error {
	if !from.CanTransitionTo(to) {
		return &execution.TransitionError{ExecutionID: id, From: from, To: to}
	}
	output, err := encodeJSON(u.Output)
	if err != nil {
		return fmt.Errorf("%w: encode output: %v", execution.ErrInvalidExecution, err)
	}
	execErr, err := encodeJSON(u.Error)
	if err != nil {
		return fmt.Errorf("%w: encode error: %v", execution.ErrInvalidExecution, err)
	}
	interrupted, err := encodeJSON(u.InterruptedNodeError)
	if err != nil {
		return fmt.Errorf("%w: encode interrupted node error: %v", execution.ErrInvalidExecution, err)
	}
	meta := u.Metadata
	if meta == nil {
		meta = map[string]any{}
	}
	metadata, err := json.Marshal(meta)
	if err != nil {
		return fmt.Errorf("%w: encode metadata: %v", execution.ErrInvalidExecution, err)
	}
	transitionID := u.TransitionID
	if transitionID == uuid.Nil {
		transitionID = uuid.New()
	}
	var claimToken any
	if u.ClaimToken != uuid.Nil {
		claimToken = u.ClaimToken
	}
	settings := map[string]string{
		"workflow.transition_id":       transitionID.String(),
		"workflow.transition_metadata": string(metadata),
	}
	return r.writer.write(ctx, settings,
		func(ctx context.Context, tx pgx.Tx) error {
			if to.IsTerminal() {
				// Lock the execution first: node writers share-lock it, so
				// they serialize with this transition (no interleaving, and
				// a consistent parent-then-node lock order).
				var current string
				err := tx.QueryRow(ctx, `SELECT status FROM executions WHERE id = $1 FOR UPDATE`, id).Scan(&current)
				if errors.Is(err, pgx.ErrNoRows) || (err == nil && current != string(from)) {
					return notApplied{fmt.Errorf("%w: execution %s is not %s", execution.ErrTransitionConflict, id, from)}
				}
				if err != nil {
					return err
				}
				if interrupted != nil {
					if _, err := tx.Exec(ctx, sweepRunningNodesSQL, id, interrupted); err != nil {
						return err
					}
				}
			}
			tag, err := tx.Exec(ctx, transitionExecutionSQL, id, string(from), string(to), output, execErr, claimToken)
			if err != nil {
				return err
			}
			if tag.RowsAffected() != 1 {
				return notApplied{fmt.Errorf("%w: execution %s is not %s", execution.ErrTransitionConflict, id, from)}
			}
			return nil
		},
		func(ctx context.Context) (bool, error) {
			var exists bool
			err := r.pool.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM execution_status_history WHERE id = $1)`, transitionID).Scan(&exists)
			return exists, err
		})
}

const historySQL = `
SELECT id, execution_id, from_status, to_status, created_at, metadata
FROM execution_status_history
WHERE execution_id = $1
ORDER BY created_at,
         CASE to_status WHEN 'PENDING' THEN 0 WHEN 'RUNNING' THEN 1 ELSE 2 END`

// History returns the execution's append-only transition history, or
// ErrExecutionNotFound when the execution does not exist.
func (r *ExecutionRepository) History(ctx context.Context, id uuid.UUID) ([]execution.StatusTransition, error) {
	rows, err := r.pool.Query(ctx, historySQL, id)
	if err != nil {
		return nil, fmt.Errorf("query execution history %s: %w", id, err)
	}
	defer rows.Close()
	var out []execution.StatusTransition
	for rows.Next() {
		var (
			t    execution.StatusTransition
			from *string
			to   string
			meta []byte
		)
		if err := rows.Scan(&t.ID, &t.ExecutionID, &from, &to, &t.CreatedAt, &meta); err != nil {
			return nil, fmt.Errorf("scan execution history: %w", err)
		}
		if from != nil {
			s := execution.ExecutionStatus(*from)
			t.From = &s
		}
		t.To = execution.ExecutionStatus(to)
		if t.Metadata, err = decodeMap(meta); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		// Every execution has at least its creation record.
		if _, err := r.Get(ctx, id); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// NodeExecutionRepository is the PostgreSQL execution.NodeExecutionRepository.
// Every write first share-locks the parent execution and requires it to be
// RUNNING (the database triggers enforce the same rule for any writer).
type NodeExecutionRepository struct {
	pool   *pgxpool.Pool
	writer *lifecycleWriter
}

var _ execution.NodeExecutionRepository = (*NodeExecutionRepository)(nil)

// NewNodeExecutionRepository uses the Store's existing connection pool.
func NewNodeExecutionRepository(store *Store) *NodeExecutionRepository {
	return &NodeExecutionRepository{pool: store.Pool, writer: &lifecycleWriter{pool: store.Pool}}
}

// requireRunningParent share-locks the execution and checks it is RUNNING.
func requireRunningParent(ctx context.Context, tx pgx.Tx, executionID uuid.UUID) error {
	var status string
	err := tx.QueryRow(ctx, `SELECT status FROM executions WHERE id = $1 FOR SHARE`, executionID).Scan(&status)
	if errors.Is(err, pgx.ErrNoRows) {
		return notApplied{fmt.Errorf("%w: %s", execution.ErrExecutionNotFound, executionID)}
	}
	if err != nil {
		return err
	}
	if status != string(execution.StatusRunning) {
		return notApplied{fmt.Errorf("%w: execution %s is %s", execution.ErrExecutionNotRunning, executionID, status)}
	}
	return nil
}

func validateNewNode(n execution.NodeExecution) error {
	if n.ID == uuid.Nil || n.ExecutionID == uuid.Nil || n.NodeID == "" || n.NodeType == "" {
		return fmt.Errorf("%w: node execution ID, execution ID, node ID and node type are required", execution.ErrInvalidExecution)
	}
	if n.Status != execution.NodeStatusPending || n.StartedAt != nil || n.FinishedAt != nil || n.Output != nil || n.Error != nil {
		return fmt.Errorf("%w: node executions are created PENDING without start, finish, output or error", execution.ErrInvalidExecution)
	}
	return nil
}

const insertNodeSQL = `
INSERT INTO node_executions (id, execution_id, node_id, node_type, status, input)
VALUES ($1, $2, $3, $4, 'PENDING', $5)`

func (r *NodeExecutionRepository) nodeStatus(ctx context.Context, id uuid.UUID) (string, bool, error) {
	var status string
	err := r.pool.QueryRow(ctx, `SELECT status FROM node_executions WHERE id = $1`, id).Scan(&status)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", false, nil
	}
	return status, err == nil, err
}

// Create inserts a PENDING node execution owned by a RUNNING execution.
func (r *NodeExecutionRepository) Create(ctx context.Context, n execution.NodeExecution) error {
	if err := validateNewNode(n); err != nil {
		return err
	}
	input, err := encodeJSON(n.Input)
	if err != nil {
		return fmt.Errorf("%w: encode node input: %v", execution.ErrInvalidExecution, err)
	}
	return r.writer.write(ctx, nil,
		func(ctx context.Context, tx pgx.Tx) error {
			if err := requireRunningParent(ctx, tx, n.ExecutionID); err != nil {
				return err
			}
			_, err := tx.Exec(ctx, insertNodeSQL, n.ID, n.ExecutionID, n.NodeID, n.NodeType, input)
			return err
		},
		func(ctx context.Context) (bool, error) {
			_, exists, err := r.nodeStatus(ctx, n.ID)
			return exists, err
		})
}

// Begin atomically creates the node execution and moves it PENDING -> RUNNING.
func (r *NodeExecutionRepository) Begin(ctx context.Context, n execution.NodeExecution, runtimeInput map[string]any) error {
	if err := validateNewNode(n); err != nil {
		return err
	}
	input, err := encodeJSON(runtimeInput)
	if err != nil {
		return fmt.Errorf("%w: encode node input: %v", execution.ErrInvalidExecution, err)
	}
	return r.writer.write(ctx, nil,
		func(ctx context.Context, tx pgx.Tx) error {
			if err := requireRunningParent(ctx, tx, n.ExecutionID); err != nil {
				return err
			}
			if _, err := tx.Exec(ctx, insertNodeSQL, n.ID, n.ExecutionID, n.NodeID, n.NodeType, nil); err != nil {
				return err
			}
			_, err := tx.Exec(ctx, transitionNodeSQL, n.ID, string(execution.NodeStatusPending), string(execution.NodeStatusRunning), input, nil, nil)
			return err
		},
		func(ctx context.Context) (bool, error) {
			_, exists, err := r.nodeStatus(ctx, n.ID)
			return exists, err
		})
}

const nodeColumns = `id, execution_id, node_id, node_type, status, input, output, error,
       created_at, updated_at, started_at, finished_at`

func scanNode(row pgx.Row) (execution.NodeExecution, error) {
	var (
		n                   execution.NodeExecution
		status              string
		input, output, eerr []byte
	)
	if err := row.Scan(&n.ID, &n.ExecutionID, &n.NodeID, &n.NodeType, &status, &input, &output, &eerr,
		&n.CreatedAt, &n.UpdatedAt, &n.StartedAt, &n.FinishedAt); err != nil {
		return execution.NodeExecution{}, err
	}
	n.Status = execution.NodeExecutionStatus(status)
	var err error
	if n.Input, err = decodeMap(input); err != nil {
		return execution.NodeExecution{}, err
	}
	if n.Output, err = decodeMap(output); err != nil {
		return execution.NodeExecution{}, err
	}
	if n.Error, err = decodeError(eerr); err != nil {
		return execution.NodeExecution{}, err
	}
	return n, nil
}

// Get loads one node execution.
func (r *NodeExecutionRepository) Get(ctx context.Context, id uuid.UUID) (execution.NodeExecution, error) {
	n, err := scanNode(r.pool.QueryRow(ctx, `SELECT `+nodeColumns+` FROM node_executions WHERE id = $1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return execution.NodeExecution{}, fmt.Errorf("%w: %s", execution.ErrNodeExecutionNotFound, id)
	}
	if err != nil {
		return execution.NodeExecution{}, fmt.Errorf("get node execution %s: %w", id, err)
	}
	return n, nil
}

// transitionNodeSQL changes a node's status and the payload that belongs to
// the target status. Timestamps are generated by triggers.
const transitionNodeSQL = `
UPDATE node_executions SET
    status = $3::text,
    input  = CASE WHEN $3::text = 'RUNNING' THEN COALESCE($4::jsonb, input) ELSE input END,
    output = CASE WHEN $3::text = 'COMPLETED' THEN $5::jsonb ELSE output END,
    error  = CASE WHEN $3::text = 'FAILED' THEN $6::jsonb ELSE error END
WHERE id = $1 AND status = $2::text`

// Transition is the node-level compare-and-set; the parent execution must be
// RUNNING.
func (r *NodeExecutionRepository) Transition(ctx context.Context, id uuid.UUID, from, to execution.NodeExecutionStatus, u execution.NodeTransitionUpdate) error {
	if !from.CanTransitionTo(to) {
		return &execution.NodeTransitionError{NodeExecutionID: id, From: from, To: to}
	}
	input, err := encodeJSON(u.Input)
	if err != nil {
		return fmt.Errorf("%w: encode node input: %v", execution.ErrInvalidExecution, err)
	}
	output, err := encodeJSON(u.Output)
	if err != nil {
		return fmt.Errorf("%w: encode node output: %v", execution.ErrInvalidExecution, err)
	}
	nodeErr, err := encodeJSON(u.Error)
	if err != nil {
		return fmt.Errorf("%w: encode node error: %v", execution.ErrInvalidExecution, err)
	}
	return r.writer.write(ctx, nil,
		func(ctx context.Context, tx pgx.Tx) error {
			var executionID uuid.UUID
			err := tx.QueryRow(ctx, `SELECT execution_id FROM node_executions WHERE id = $1`, id).Scan(&executionID)
			if errors.Is(err, pgx.ErrNoRows) {
				return notApplied{fmt.Errorf("%w: node execution %s", execution.ErrTransitionConflict, id)}
			}
			if err != nil {
				return err
			}
			if err := requireRunningParent(ctx, tx, executionID); err != nil {
				return err
			}
			tag, err := tx.Exec(ctx, transitionNodeSQL, id, string(from), string(to), input, output, nodeErr)
			if err != nil {
				return err
			}
			if tag.RowsAffected() != 1 {
				return notApplied{fmt.Errorf("%w: node execution %s is not %s", execution.ErrTransitionConflict, id, from)}
			}
			return nil
		},
		func(ctx context.Context) (bool, error) {
			status, _, err := r.nodeStatus(ctx, id)
			return status == string(to), err
		})
}

// ListByExecution returns an execution's node records in start order.
func (r *NodeExecutionRepository) ListByExecution(ctx context.Context, executionID uuid.UUID) ([]execution.NodeExecution, error) {
	rows, err := r.pool.Query(ctx, `SELECT `+nodeColumns+` FROM node_executions
WHERE execution_id = $1 ORDER BY created_at, started_at NULLS LAST, node_id`, executionID)
	if err != nil {
		return nil, fmt.Errorf("list node executions %s: %w", executionID, err)
	}
	defer rows.Close()
	var out []execution.NodeExecution
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, fmt.Errorf("scan node execution: %w", err)
		}
		out = append(out, n)
	}
	return out, rows.Err()
}

// encodeJSON marshals v for a JSONB parameter; a nil map/pointer becomes SQL
// NULL. encoding/json sorts map keys, so the encoding is deterministic.
func encodeJSON(v any) ([]byte, error) {
	switch typed := v.(type) {
	case nil:
		return nil, nil
	case map[string]any:
		if typed == nil {
			return nil, nil
		}
	case *execution.ExecutionError:
		if typed == nil {
			return nil, nil
		}
	}
	return json.Marshal(v)
}

// decodeMap decodes a JSONB object preserving numeric precision: numbers
// become json.Number, so integers beyond 2^53 survive the round trip.
func decodeMap(raw []byte) (map[string]any, error) {
	if raw == nil {
		return nil, nil
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var m map[string]any
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("decode JSONB object: %w", err)
	}
	return m, nil
}

func decodeError(raw []byte) (*execution.ExecutionError, error) {
	if raw == nil {
		return nil, nil
	}
	var e execution.ExecutionError
	if err := json.Unmarshal(raw, &e); err != nil {
		return nil, fmt.Errorf("decode execution error: %w", err)
	}
	return &e, nil
}
