package execution

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// IDs follow the repository-wide convention of uuid.UUID for durable records.

// Execution is one durable run of an exact, immutable workflow version.
//
// It is a read snapshot. Its Status changes only through ExecutionStateMachine
// (backed by ExecutionRepository.Transition, a conditional update); assigning
// the field on a value has no persistence path, and repositories expose no
// generic update/save method.
type Execution struct {
	ID                uuid.UUID
	WorkflowID        uuid.UUID
	WorkflowVersionID uuid.UUID

	Status ExecutionStatus

	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError

	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time

	// ClaimToken identifies the claim (worker) that moved the execution to
	// RUNNING. Nil while PENDING, and for legacy rows claimed before Phase 8.
	ClaimToken *uuid.UUID
}

// NodeExecution records the execution of one workflow node inside an
// Execution. NodeType is required by the existing node_executions schema.
type NodeExecution struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	NodeID      string
	NodeType    string

	Status NodeExecutionStatus

	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError

	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time
}

// StatusTransition is one append-only execution_status_history record.
// From is nil for the creation record (NULL -> PENDING).
type StatusTransition struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	From        *ExecutionStatus
	To          ExecutionStatus
	CreatedAt   time.Time
	Metadata    map[string]any
}

// TransitionUpdate carries the data written atomically with a status change.
// Output is only accepted for COMPLETED and Error is required for FAILED.
type TransitionUpdate struct {
	Output   map[string]any
	Error    *ExecutionError
	Metadata map[string]any // stored on the database-generated history record

	// ClaimToken is required for PENDING -> RUNNING and recorded on the row.
	ClaimToken uuid.UUID
	// TransitionID becomes the history record's ID. It is the commit marker
	// used to resolve ambiguous writes; generated by the state machine.
	TransitionID uuid.UUID
	// InterruptedNodeError is applied (with each node's ID) to node records
	// still RUNNING when the execution moves to FAILED or CANCELLED, in the
	// same transaction, so a terminal execution never has RUNNING nodes.
	InterruptedNodeError *ExecutionError
}

// NodeTransitionUpdate carries the data written atomically with a node status
// change: Input on RUNNING, Output on COMPLETED, Error on FAILED.
type NodeTransitionUpdate struct {
	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError
}

// ExecutionRepository is the persistence boundary for executions. Writes must
// be atomic, bounded by ctx, and either definitely applied, definitely not
// applied, or reported as ErrOutcomeUnknown.
type ExecutionRepository interface {
	// Create inserts a PENDING execution (its creation history record is
	// generated by the store) and returns the persisted row. Any other status
	// is rejected.
	Create(ctx context.Context, execution Execution) (Execution, error)
	// Get returns ErrExecutionNotFound when the execution does not exist.
	Get(ctx context.Context, id uuid.UUID) (Execution, error)
	// Transition atomically moves the execution from -> to only if it is
	// currently in from, applies update, and records history in the same
	// transaction. It returns ErrTransitionConflict when no row matched.
	Transition(ctx context.Context, id uuid.UUID, from, to ExecutionStatus, update TransitionUpdate) error
	// History returns the execution's status history, oldest first, or
	// ErrExecutionNotFound when the execution does not exist.
	History(ctx context.Context, id uuid.UUID) ([]StatusTransition, error)
}

// NodeExecutionRepository is the persistence boundary for node executions.
// Every write requires the parent execution to be RUNNING
// (ErrExecutionNotRunning otherwise).
type NodeExecutionRepository interface {
	// Create inserts a PENDING node execution owned by a RUNNING execution.
	Create(ctx context.Context, execution NodeExecution) error
	// Begin atomically creates the node execution and moves it
	// PENDING -> RUNNING with input, so a started node is never left PENDING.
	Begin(ctx context.Context, execution NodeExecution, input map[string]any) error
	// Get returns ErrNodeExecutionNotFound when the record does not exist.
	Get(ctx context.Context, id uuid.UUID) (NodeExecution, error)
	// Transition is the node-level conditional update; see ExecutionRepository.
	Transition(ctx context.Context, id uuid.UUID, from, to NodeExecutionStatus, update NodeTransitionUpdate) error
	// ListByExecution returns an execution's node records, oldest first.
	ListByExecution(ctx context.Context, executionID uuid.UUID) ([]NodeExecution, error)
}

// DefaultWriteTimeout bounds every lifecycle persistence operation.
const DefaultWriteTimeout = 10 * time.Second

// PersistenceOptions configures lifecycle persistence.
type PersistenceOptions struct {
	// WriteTimeout bounds each lifecycle database operation (default
	// DefaultWriteTimeout). Operations run on a context detached from the
	// caller's cancellation, so a started write is always resolved.
	WriteTimeout time.Duration
}

// persistContext detaches lifecycle persistence from caller cancellation (a
// cancelled run must still record that it was cancelled) while giving it its
// own deadline, so persistence can never block forever.
func persistContext(ctx context.Context, opts PersistenceOptions) (context.Context, context.CancelFunc) {
	timeout := opts.WriteTimeout
	if timeout <= 0 {
		timeout = DefaultWriteTimeout
	}
	return context.WithTimeout(context.WithoutCancel(ctx), timeout)
}
