package execution

import (
	"context"
	"time"

	"github.com/google/uuid"

	"workflow-optimizer/internal/node"
)

// IDs follow the repository-wide convention of uuid.UUID for durable records.

// Execution is one durable run of an exact, immutable workflow version.
//
// It is a read snapshot. Its Status changes only through ExecutionStateMachine
// (backed by ExecutionRepository.Transition, a conditional update); assigning
// the field on a value has no persistence path, and repositories expose no
// generic update/save method.
type Execution struct {
	ID                uuid.UUID
	WorkflowID        uuid.UUID
	WorkflowVersionID uuid.UUID

	Status ExecutionStatus

	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError

	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time

	// ClaimToken identifies the claim (worker) that moved the execution to
	// RUNNING. Nil while PENDING, and for legacy rows claimed before Phase 8.
	ClaimToken *uuid.UUID

	// Phase 10 reliability state (maintained by the database).

	// Attempt is the number of claims so far: the current attempt while
	// RUNNING, the last attempt when terminal, 0 before the first claim.
	Attempt int
	// MaxAttempts bounds Attempt; it is fixed at creation (0 on Create uses
	// the store's default of 1, i.e. no retries).
	MaxAttempts int
	// Timeout is the execution's total time budget, fixed at creation (0 =
	// none). DeadlineAt = first claim + Timeout, set by the database.
	Timeout    time.Duration
	DeadlineAt *time.Time
	// NextAttemptAt is when a scheduled retry becomes due (PENDING only).
	NextAttemptAt *time.Time
	// LastError is the failure of the most recent attempt that was retried.
	LastError *ExecutionError
	// CancelRequested reports a durable cancellation request.
	CancelRequested bool
}

// NodeExecution records the execution of one workflow node inside an
// Execution. NodeType is required by the existing node_executions schema.
type NodeExecution struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	NodeID      string
	NodeType    string

	Status NodeExecutionStatus

	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError

	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time

	// Attempt numbers the node's invocations within its execution (assigned
	// by the store). ExecutionAttempt is the execution attempt that wrote the
	// record (assigned by the store from the owning claim).
	Attempt          int
	ExecutionAttempt int
	// ClaimToken fences the write: when set, the store accepts the record
	// only while this exact claim owns the RUNNING execution, and the record
	// can only change while that claim still owns it (a worker whose attempt
	// was recovered gets ErrLeaseLost). uuid.Nil writes unfenced under the
	// current claim (Phase 8 callers).
	ClaimToken uuid.UUID
	// SideEffects is the node definition's declaration, persisted so that
	// recovery can tell whether an interrupted node may be run again.
	// SideEffectsUnknown is read back for records written before it was
	// recorded.
	SideEffects node.SideEffects
	// OutputValues is the typed output of a COMPLETED node, used to resume a
	// retried execution without re-running the node.
	OutputValues map[string]node.Value
}

// StatusTransition is one append-only execution_status_history record.
// From is nil for the creation record (NULL -> PENDING).
type StatusTransition struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	From        *ExecutionStatus
	To          ExecutionStatus
	CreatedAt   time.Time
	Metadata    map[string]any
	// Attempt is the execution attempt the transition belongs to.
	Attempt int
}

// TransitionUpdate carries the data written atomically with a status change.
// Output is only accepted for COMPLETED and Error is required for FAILED.
type TransitionUpdate struct {
	Output   map[string]any
	Error    *ExecutionError
	Metadata map[string]any // stored on the database-generated history record

	// ClaimToken is required for PENDING -> RUNNING and recorded on the row.
	ClaimToken uuid.UUID
	// TransitionID becomes the history record's ID. It is the commit marker
	// used to resolve ambiguous writes; generated by the state machine.
	TransitionID uuid.UUID
	// InterruptedNodeError is applied (with each node's ID) to node records
	// still RUNNING when the execution moves to FAILED, CANCELLED or (Phase
	// 10) back to PENDING, in the same transaction.
	InterruptedNodeError *ExecutionError

	// Phase 10.

	// Owner fences the write: when set, it applies only while the execution
	// is still claimed with this token (a worker that lost its lease cannot
	// finalize or reschedule an attempt it no longer owns).
	Owner uuid.UUID
	// Lease, on a claim (-> RUNNING), records the owning worker's lease in the
	// same transaction.
	Lease *LeaseGrant
	// RetryDelay and LastError are required for RUNNING -> PENDING: the retry
	// becomes due RetryDelay after the transition (database clock).
	RetryDelay time.Duration
	LastError  *ExecutionError
	// DeadLetter, on -> FAILED, records why the execution stopped retrying,
	// in the same transaction.
	DeadLetter DeadLetterReason
}

// LeaseGrant is the ownership recorded with a claim.
type LeaseGrant struct {
	Owner    string
	Duration time.Duration
}

// DeadLetterReason explains why a retryable failure stopped being retried.
type DeadLetterReason string

const (
	DeadLetterAttemptsExhausted DeadLetterReason = "attempts_exhausted"
	DeadLetterDeadlineExceeded  DeadLetterReason = "deadline_exceeded"
	// DeadLetterRetryUnsafe: the attempt was lost while a node with unsafe
	// (or unknown) side effects was running; it may have applied them, so
	// the execution is not run again.
	DeadLetterRetryUnsafe DeadLetterReason = "retry_unsafe"
)

// SideEffectsUnknown is the side-effect declaration read back for node
// records written before declarations were persisted. Recovery treats it
// like node.SideEffectsUnsafe.
const SideEffectsUnknown node.SideEffects = "unknown"

// DeadLetter is the authoritative record of an execution that stopped
// retrying.
type DeadLetter struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	Attempt     int
	Error       ExecutionError
	Reason      DeadLetterReason
	CreatedAt   time.Time
}

// LeaseState is the result of renewing a lease.
type LeaseState struct {
	// Held is false once the attempt is no longer owned by this claim (the
	// execution left RUNNING, or the lease expired and may be recovered).
	Held bool
	// CancelRequested reports a durable cancellation request.
	CancelRequested bool
}

// LeaseStore persists worker ownership of RUNNING attempts.
type LeaseStore interface {
	// Renew extends the lease of the attempt claimed with claimToken by d,
	// only while it is still valid; it never revives an expired lease.
	Renew(ctx context.Context, executionID, claimToken uuid.UUID, d time.Duration) (LeaseState, error)
}

// LeaseKeeper keeps a claimed attempt's lease alive while it runs.
type LeaseKeeper interface {
	// Keep returns a context derived from ctx that is cancelled with cause
	// ErrLeaseLost when ownership is lost, or ErrCancelRequested when the
	// execution's cancellation is requested. stop ends the renewals.
	Keep(ctx context.Context, executionID, claimToken uuid.UUID) (kept context.Context, stop func())
}

// CancellationStore records durable cancellation requests.
type CancellationStore interface {
	RequestCancel(ctx context.Context, executionID uuid.UUID) error
}

// NodeTransitionUpdate carries the data written atomically with a node status
// change: Input on RUNNING, Output on COMPLETED, Error on FAILED.
type NodeTransitionUpdate struct {
	Input  map[string]any
	Output map[string]any
	Error  *ExecutionError
	// OutputValues (typed output) may accompany Output on COMPLETED.
	OutputValues map[string]node.Value
}

// ExecutionRepository is the persistence boundary for executions. Writes must
// be atomic, bounded by ctx, and either definitely applied, definitely not
// applied, or reported as ErrOutcomeUnknown.
type ExecutionRepository interface {
	// Create inserts a PENDING execution (its creation history record is
	// generated by the store) and returns the persisted row. Any other status
	// is rejected.
	Create(ctx context.Context, execution Execution) (Execution, error)
	// Get returns ErrExecutionNotFound when the execution does not exist.
	Get(ctx context.Context, id uuid.UUID) (Execution, error)
	// Transition atomically moves the execution from -> to only if it is
	// currently in from, applies update, and records history in the same
	// transaction. It returns ErrTransitionConflict when no row matched.
	Transition(ctx context.Context, id uuid.UUID, from, to ExecutionStatus, update TransitionUpdate) error
	// History returns the execution's status history, oldest first, or
	// ErrExecutionNotFound when the execution does not exist.
	History(ctx context.Context, id uuid.UUID) ([]StatusTransition, error)
}

// NodeExecutionRepository is the persistence boundary for node executions.
// Every write requires the parent execution to be RUNNING
// (ErrExecutionNotRunning otherwise).
type NodeExecutionRepository interface {
	// Create inserts a PENDING node execution owned by a RUNNING execution.
	Create(ctx context.Context, execution NodeExecution) error
	// Begin atomically creates the node execution and moves it
	// PENDING -> RUNNING with input, so a started node is never left PENDING.
	Begin(ctx context.Context, execution NodeExecution, input map[string]any) error
	// Get returns ErrNodeExecutionNotFound when the record does not exist.
	Get(ctx context.Context, id uuid.UUID) (NodeExecution, error)
	// Transition is the node-level conditional update; see ExecutionRepository.
	Transition(ctx context.Context, id uuid.UUID, from, to NodeExecutionStatus, update NodeTransitionUpdate) error
	// ListByExecution returns an execution's node records, oldest first.
	ListByExecution(ctx context.Context, executionID uuid.UUID) ([]NodeExecution, error)
}

// DefaultWriteTimeout bounds every lifecycle persistence operation.
const DefaultWriteTimeout = 10 * time.Second

// PersistenceOptions configures lifecycle persistence.
type PersistenceOptions struct {
	// WriteTimeout bounds each lifecycle database operation (default
	// DefaultWriteTimeout). Operations run on a context detached from the
	// caller's cancellation, so a started write is always resolved.
	WriteTimeout time.Duration
}

// persistContext detaches lifecycle persistence from caller cancellation (a
// cancelled run must still record that it was cancelled) while giving it its
// own deadline, so persistence can never block forever.
func persistContext(ctx context.Context, opts PersistenceOptions) (context.Context, context.CancelFunc) {
	timeout := opts.WriteTimeout
	if timeout <= 0 {
		timeout = DefaultWriteTimeout
	}
	return context.WithTimeout(context.WithoutCancel(ctx), timeout)
}
