package llm

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"

	"workflow-optimizer/internal/credential"
	"workflow-optimizer/internal/node"
	providerllm "workflow-optimizer/internal/provider/llm"
)

// NodeType is the stable identifier for LLM nodes.
const NodeType = "llm"

// Error codes reported by the LLM node for credential problems (never
// retryable) and configuration problems.
const (
	ErrCodeCredentialNotFound         node.ErrorCode = "CREDENTIAL_NOT_FOUND"
	ErrCodeCredentialDecryptionFailed node.ErrorCode = "CREDENTIAL_DECRYPTION_FAILED"
	ErrCodeCredentialProviderMismatch node.ErrorCode = "CREDENTIAL_PROVIDER_MISMATCH"
	ErrCodeCredentialInvalid          node.ErrorCode = "CREDENTIAL_INVALID"
	ErrCodeProviderNotFound           node.ErrorCode = "PROVIDER_NOT_FOUND"
)

// Definition returns the canonical metadata definition for an LLM node
// without provider metadata (see DefinitionFor).
func Definition() node.NodeDefinition {
	return DefinitionFor(nil)
}

// DefinitionFor returns the LLM node definition whose provider and model
// options describe the given providers (providerllm.Describe of the
// application's provider registry). The node itself stays provider-neutral:
// options are metadata; the provider registry decides at run time.
func DefinitionFor(providers []providerllm.Info) node.NodeDefinition {
	providerField := node.NewConfigField("provider", node.ValueTypeString, true, "openai", "Which AI provider runs the model.").WithLabel("Provider")
	modelField := node.NewConfigField("model", node.ValueTypeString, true, "gpt-5", "The model to use. Pick one or enter another model ID.").WithLabel("Model")
	if len(providers) > 0 {
		var provOpts, modelOpts []node.ConfigOption
		for _, p := range providers {
			provOpts = append(provOpts, node.Option(p.Name, p.Label))
			for _, m := range p.Models {
				modelOpts = append(modelOpts, node.ConfigOption{Value: m.ID, Label: m.Label, When: map[string]any{"provider": p.Name}})
			}
		}
		providerField = providerField.WithOptions(provOpts...)
		modelField = modelField.WithOptions(modelOpts...).WithCustom()
	}
	return node.NodeDefinition{
		Type:        NodeType,
		Name:        "LLM",
		Description: "Sends a prompt to a language model and returns its response.",
		Category:    node.CategoryAI,
		Inputs: []node.PortDefinition{
			node.NewPortDefinition("prompt", node.ValueTypeString, false, "Prompt sent to the model (overrides the User prompt setting)"),
			node.NewPortDefinition("system", node.ValueTypeString, false, "System instructions (overrides the System prompt setting)"),
		},
		Outputs: []node.PortDefinition{
			node.NewPortDefinition("response", node.ValueTypeString, true, "Text output generated by the model"),
			node.NewPortDefinition("model", node.ValueTypeString, false, "Model that produced the response"),
			node.NewPortDefinition("finish_reason", node.ValueTypeString, false, "Why generation stopped"),
			node.NewPortDefinition("usage", node.ValueTypeJSON, false, "Token usage: input_tokens, output_tokens, total_tokens"),
		},
		Config: []node.ConfigField{
			providerField,
			modelField,
			node.NewConfigField("credential_id", node.ValueTypeString, false, "", "Workspace credential identifier").WithLabel("Credential"),
			node.NewConfigField("system", node.ValueTypeString, false, "", "Instructions that shape how the model answers. Used when the system input is not connected; {{variables}} are filled in.").WithLabel("System prompt").WithMultiline(),
			node.NewConfigField("prompt", node.ValueTypeString, false, "", "What to ask the model. Used when the prompt input is not connected; {{variables}} are filled in.").WithLabel("User prompt").WithMultiline(),
			node.NewConfigField("temperature", node.ValueTypeNumber, false, 0.2, "Higher values give more varied answers.").WithLabel("Temperature").WithRange(node.Float(0), node.Float(2), node.Float(0.1)),
			node.NewConfigField("max_tokens", node.ValueTypeNumber, false, nil, "Upper limit on the length of the response.").WithLabel("Max tokens").WithRange(node.Float(1), nil, node.Float(1)),
		},
	}
}

// Dependencies are the LLM node's collaborators. Both are interfaces: the
// node never sees how providers talk to vendors or how credentials are
// stored.
type Dependencies struct {
	// Providers selects the provider named by config.provider.
	Providers providerllm.Registry
	// Credentials resolves config.credential_id inside the execution's
	// workspace.
	Credentials credential.Resolver
}

// Node is the executable LLM node:
//
//	inputs -> LLMRequest -> provider registry -> credential resolver
//	       -> provider.Generate -> NodeOutput
//
// It does not touch PostgreSQL or Redis, contain vendor code, switch on
// providers, retry, or manage execution state. Provider and credential
// failures are returned as classified *node.NodeError values; retrying is the
// execution engine's decision.
type Node struct {
	deps Dependencies
}

// New constructs an LLM node. A node built without a provider registry is the
// unwired Phase 4 node: it returns a fixed stub response (used by graph-level
// tests that need an LLM node without any provider); production wiring always
// supplies Dependencies.
func New(deps Dependencies) *Node {
	return &Node{deps: deps}
}

// Type returns the unique node type identifier.
func (n *Node) Type() string {
	return NodeType
}

// secretConfigKeys must never appear in a workflow's node config: secrets
// live in credentials, referenced by credential_id.
var secretConfigKeys = []string{"api_key", "apikey", "secret", "token", "password", "authorization"}

// Execute performs language model generation via the provider abstraction.
func (n *Node) Execute(ctx context.Context, in node.NodeInput) (node.NodeOutput, error) {
	if err := ctx.Err(); err != nil {
		return node.NodeOutput{}, err
	}
	promptText := portOrConfig(in, "prompt")
	systemText := portOrConfig(in, "system")

	if n.deps.Providers == nil {
		out := node.NewNodeOutput(nil)
		out.SetPort("response", node.NewStringValue("stub:llm response"))
		return out, nil
	}

	for _, k := range secretConfigKeys {
		if _, present := in.Config[k]; present {
			return node.NodeOutput{}, configError(fmt.Sprintf("config must not contain %q: reference a workspace credential with credential_id", k))
		}
	}
	providerName, _ := in.GetStringConfig("provider")
	model, _ := in.GetStringConfig("model")
	if strings.TrimSpace(providerName) == "" || strings.TrimSpace(model) == "" {
		return node.NodeOutput{}, configError("provider and model are required")
	}
	if strings.TrimSpace(promptText) == "" {
		return node.NodeOutput{}, configError("a prompt is required: connect the prompt input or set User prompt")
	}
	req := providerllm.Request{
		Model:    model,
		System:   systemText,
		Messages: []providerllm.Message{{Role: providerllm.RoleUser, Content: promptText}},
	}
	if t, ok := in.GetNumberConfig("temperature"); ok {
		req.Temperature = &t
	}
	if m, ok := in.GetNumberConfig("max_tokens"); ok {
		if m < 1 || m != float64(int(m)) {
			return node.NodeOutput{}, configError("max_tokens must be a positive integer")
		}
		maxTokens := int(m)
		req.MaxTokens = &maxTokens
	}

	provider, err := n.deps.Providers.Get(providerName)
	if err != nil {
		return node.NodeOutput{}, node.WrapNodeError(ErrCodeProviderNotFound, fmt.Sprintf("llm provider %q is not registered", providerName), false, err)
	}

	resolved, err := n.resolveCredential(ctx, in, providerName)
	if err != nil {
		return node.NodeOutput{}, err
	}
	req.Credential = resolved
	resp, err := provider.Generate(ctx, req)
	req.Credential = credential.ResolvedCredential{} // the secret is not kept
	if err != nil {
		return node.NodeOutput{}, classifyProviderError(err)
	}

	out := node.NewNodeOutput(nil)
	out.SetPort("response", node.NewStringValue(resp.Content))
	out.SetPort("model", node.NewStringValue(resp.Model))
	out.SetPort("finish_reason", node.NewStringValue(resp.FinishReason))
	out.SetPort("usage", node.NewJSONValue(map[string]any{
		"input_tokens":  float64(resp.Usage.InputTokens),
		"output_tokens": float64(resp.Usage.OutputTokens),
		"total_tokens":  float64(resp.Usage.TotalTokens),
	}))
	return out, nil
}

func (n *Node) resolveCredential(ctx context.Context, in node.NodeInput, providerName string) (credential.ResolvedCredential, error) {
	raw, _ := in.GetStringConfig("credential_id")
	if strings.TrimSpace(raw) == "" {
		return credential.ResolvedCredential{}, node.NewNodeError(ErrCodeCredentialInvalid, "credential_id is required", false)
	}
	id, err := uuid.Parse(strings.TrimSpace(raw))
	if err != nil {
		return credential.ResolvedCredential{}, node.NewNodeError(ErrCodeCredentialInvalid, "credential_id is not a valid identifier", false)
	}
	if n.deps.Credentials == nil {
		return credential.ResolvedCredential{}, node.NewNodeError(ErrCodeCredentialInvalid, "credential resolution is not configured", false)
	}
	resolved, err := n.deps.Credentials.Resolve(ctx, in.Scope.WorkspaceID, id, providerName)
	if err != nil {
		return credential.ResolvedCredential{}, classifyCredentialError(err)
	}
	return resolved, nil
}

func configError(msg string) error {
	return node.NewNodeError(node.ErrCodeConfiguration, msg, false)
}

// classifyCredentialError maps credential failures to their non-retryable
// codes; anything else (e.g. the credential store being unreachable) is a
// transient failure.
func classifyCredentialError(err error) error {
	var code node.ErrorCode
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	case errors.Is(err, credential.ErrNotFound):
		code = ErrCodeCredentialNotFound
	case errors.Is(err, credential.ErrDecryptionFailed):
		code = ErrCodeCredentialDecryptionFailed
	case errors.Is(err, credential.ErrProviderMismatch):
		code = ErrCodeCredentialProviderMismatch
	case errors.Is(err, credential.ErrInvalid):
		code = ErrCodeCredentialInvalid
	default:
		return node.WrapNodeError(node.ErrCodeUnavailable, "credential could not be resolved", true, err)
	}
	return node.WrapNodeError(code, "credential could not be used", false, err)
}

// classifyProviderError carries the provider's platform-level classification
// (code, retryability, Retry-After, not-applied) into a NodeError, which is
// what the Phase 10 engine reads. Cancellation and deadlines pass through
// unchanged so the engine sees them as such.
func classifyProviderError(err error) error {
	var perr *providerllm.Error
	var typed *node.NodeError
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	case errors.As(err, &typed):
		return err
	case errors.Is(err, credential.ErrInvalid):
		return node.WrapNodeError(ErrCodeCredentialInvalid, "credential could not be used", false, err)
	case errors.As(err, &perr):
		e := node.WrapNodeError(node.ErrorCode(perr.Code), "llm generation failed", perr.Retryable, perr)
		e.Source = node.SourceProvider
		e.RetryAfter = perr.RetryAfter
		e.NotApplied = perr.NotApplied
		e.Details = map[string]any{"provider": perr.Provider}
		if perr.StatusCode != 0 {
			e.Details["status_code"] = perr.StatusCode
		}
		return e
	default:
		e := node.WrapNodeError(node.ErrCodeExecutionFailed, "llm generation failed", true, err)
		e.Source = node.SourceProvider
		return e
	}
}

// portOrConfig is the text on an input port when it is connected, else the
// (already resolved) configuration field of the same name.
func portOrConfig(in node.NodeInput, name string) string {
	if v, ok := in.GetPort(name); ok {
		return textOf(v)
	}
	s, _ := in.GetStringConfig(name)
	return s
}

// textOf returns a string value as is and renders any other value (for
// example a json port holding the workflow input object) as JSON text.
func textOf(v node.Value) string {
	if s, ok := v.String(); ok {
		return s
	}
	if v.Data == nil {
		return ""
	}
	b, err := json.Marshal(v.Data)
	if err != nil {
		return ""
	}
	return string(b)
}
