package llm

import (
	"context"

	"workflow-optimizer/internal/node"
	providerllm "workflow-optimizer/internal/provider/llm"
)

// NodeType is the stable identifier for LLM nodes.
const NodeType = "llm"

// Definition returns the canonical metadata definition for an LLM node.
func Definition() node.NodeDefinition {
	return node.NodeDefinition{
		Type:        NodeType,
		Name:        "LLM",
		Description: "Executes generative text inference via a provider-neutral AI provider.",
		Category:    node.CategoryAI,
		Inputs: []node.PortDefinition{
			node.NewPortDefinition("prompt", node.ValueTypeString, true, "Prompt sent to the language model"),
			node.NewPortDefinition("system", node.ValueTypeString, false, "Optional system instructions"),
		},
		Outputs: []node.PortDefinition{
			node.NewPortDefinition("response", node.ValueTypeString, true, "Text output generated by the model"),
		},
		Config: []node.ConfigField{
			node.NewConfigField("provider", node.ValueTypeString, true, "openai", "AI provider identifier"),
			node.NewConfigField("model", node.ValueTypeString, true, "gpt-5", "Model name or checkpoint"),
			node.NewConfigField("temperature", node.ValueTypeNumber, false, 0.2, "Sampling temperature"),
			node.NewConfigField("credential_id", node.ValueTypeString, false, "", "Workspace credential identifier"),
		},
	}
}

// Node is the executable contract implementation for LLM nodes.
// It receives its provider dependency at construction time and does NOT couple
// directly to any external HTTP API or specific provider SDK.
type Node struct {
	provider providerllm.Provider
}

// New constructs an executable LLM node with injected provider dependency.
func New(provider providerllm.Provider) *Node {
	return &Node{
		provider: provider,
	}
}

// Type returns the unique node type identifier.
func (n *Node) Type() string {
	return NodeType
}

// Execute performs language model generation via the provider abstraction.
func (n *Node) Execute(ctx context.Context, in node.NodeInput) (node.NodeOutput, error) {
	if err := ctx.Err(); err != nil {
		return node.NodeOutput{}, err
	}

	promptVal, _ := in.GetPort("prompt")
	promptText, _ := promptVal.String()
	systemVal, _ := in.GetPort("system")
	systemText, _ := systemVal.String()

	model, _ := in.GetStringConfig("model")

	var responseText string
	if n.provider != nil {
		resp, err := n.provider.Generate(ctx, providerllm.Request{
			Prompt: promptText,
			System: systemText,
			Model:  model,
		})
		if err != nil {
			return node.NodeOutput{}, node.WrapNodeError(node.ErrCodeExecutionFailed, "llm generation failed", true, err)
		}
		responseText = resp.Text
	} else {
		// Minimal stub response for testing when provider is nil
		responseText = "stub:llm response"
	}

	out := node.NewNodeOutput(nil)
	out.SetPort("response", node.NewStringValue(responseText))
	return out, nil
}
